recipe: default.v1
language: en
#Sadditional_languages:
#  - zh-TW  #Traditional  Chinese
#  - zh-CN  # Simplified Chinese

pipeline:
  - name: SearchReadyLLMCommandGenerator
    llm:
      model_group: ollama_llm
    #prompt_template: prompts/command-generator.jinja2
    flow_retrieval:
      active: false
    max_retries: 3
    retry_delay: 1.0

policies:
  - name: FlowPolicy
  - name: EnterpriseSearchPolicy
    llm:
      model_group: ollama_llm
    embeddings:
      model_group: hf_emb
    vector_store:
      type: "faiss"
      source: "./docs"
      debug: true
    top_k: 5
    use_generative_llm: true
    prompt_template: prompts/enterprise-search-policy-template.jinja2
assistant_id: 20251127-124921-unsorted-bardolino
