recipe: default.v1
language: en
additional_languages:
  - zh-TW
  - zh-CN

pipeline:
  - name: SearchReadyLLMCommandGenerator
    llm:
      model_group: ollama_llm
    flow_retrieval:
      embeddings:
        model_group: hf_emb
    max_retries: 3
    retry_delay: 1.0

policies:
  - name: FlowPolicy
  - name: EnterpriseSearchPolicy
    llm:
      model_group: ollama_llm
    embeddings:
      model_group: hf_emb
    vector_store:
      type: "faiss"
      source: "./docs"
    prompt_template: prompts/enterprise-search-policy-template.jinja2
assistant_id: 20251127-124921-unsorted-bardolino
